---
- name: create custom network
  docker_network:
    name: mynetwork
    ipam_config:
      - subnet: 10.0.0.0/24
        gateway: 10.0.0.1
        iprange: 10.0.0.0/26
        aux_addresses:
          host1: 10.0.0.2
          host2: 10.0.0.3
